---
- name: create VPC
  amazon.aws.ec2_vpc_net:
    state: present
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ aws_region }}"
    multi_ok: no
    name: "{{ vpc_prefix }}_VPC"
  tags:
    - provisioning
  register: vpc_data
- name: create subnet
  amazon.aws.ec2_vpc_subnet:
    state: present
    region: "{{ aws_region }}"
    az: "{{ aws_az_1 }}"
    cidr: "{{ vpc_subnet_cidr }}"
    vpc_id: "{{ vpc_data.vpc.id }}"
    tags:
      Name: "{{ vpc_prefix }}_SUBNET"
  tags:
    - provisioning
  register: subnet_data
- name: create second subnet for database
  amazon.aws.ec2_vpc_subnet:
    state: present
    region: "{{ aws_region }}"
    az: "{{ aws_az_2 }}"
    cidr: "{{ rds_subnet_cidr }}"
    vpc_id: "{{ vpc_data.vpc.id }}"
    tags:
      Name: "{{ vpc_prefix }}_DB_SUBNET"
  tags:
    - provisioning
  register: subnet_data_2
- name: add internet gateway to VPC
  amazon.aws.ec2_vpc_igw:
    state: present
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_data.vpc.id }}"
    tags:
      Name: "{{ vpc_prefix }}_IGW"
  tags:
    - provisioning
  register: igw_data
- name: add routing table
  amazon.aws.ec2_vpc_route_table:
    state: present
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_data.vpc.id }}"
    tags:
      Name: "{{ vpc_prefix }}_RTBL"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw_data.gateway_id }}"
    subnets:
      - "{{ subnet_data.subnet.id }}"
  tags:
    - provisioning
  register: route_table_data
- name: add security group
  amazon.aws.ec2_group:
    state: present
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_data.vpc.id }}"
    name: "{{ vpc_prefix }}_SECGRP"
    description: "{{ secgroup_desc }}"
    purge_rules: true
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ secgroup_ssh_allowed_instructor_cidr }}"
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
  tags:
    - provisioning
  register: secgroup_data
